version: '3.8'

services:
  mydb:
    image: mysql:latest
    container_name: mydb
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  wp:
    image: wordpress:latest
    container_name: wp
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - mydb
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mysql_data:
  wordpress_data:
